[pytest]
testpaths =
    Playwright_Basics
    Unittest_Basics
addopts = --slowmo 500 --browser chromium --browser firefox --tracing retain-on-failure --video=retain-on-failure --screenshot=only-on-failure --reruns 2 --timeout 60 --html=report.html -s