[pytest]
testpaths =
    Playwright Basics
    Unittest Basics
addopts = --slowmo 500 --browser chromium --browser firefox -n auto --tracing retain-on-failure --video=retain-on-failure --screenshot=only-on-failure --reruns 2 --timeout 60 --html=report.html
