[pytest]
testpaths =
    Playwright_Basics
    Unittest_Basics
markers =
    smoke: mark a test as a smoke test.
    regression: mark a test as a regression test.
addopts = --slowmo 500 --browser chromium --browser firefox --tracing retain-on-failure --video=retain-on-failure --screenshot=only-on-failure --timeout 60 --html=report.html -s -q